#!/usr/bin/env python3
"""Tests Structure Break - batches."""
import sys; sys.path.insert(0,'.')
import config as CFG
exec(open('bt_test_combos.py').read().split('def main')[0])

def base():
    CFG.STRUCTURE_SWING_WINDOW=5; CFG.STRUCTURE_LOOKBACK=60
    CFG.STRUCTURE_BREAK_LOOKBACK=10; CFG.STRUCTURE_MIN_BREAK_VOLUME=2.0
    CFG.STRUCTURE_RETEST_LOOKBACK=8; CFG.STRUCTURE_RETEST_TOLERANCE_ATR=0.5
    CFG.STRUCTURE_SL_BUFFER_ATR=1.0; CFG.STRUCTURE_ADX_MIN=15
    CFG.STRUCTURE_MIN_VOLUME_RATIO=1.0; CFG.STRUCTURE_MIN_ATR_PCT=0.10

def run(label, syms, overrides=None, adx=None):
    base()
    if adx is not None: CFG.ADX_MIN = adx
    if overrides:
        for k,v in overrides.items(): setattr(CFG,k,v)
    a = adx if adx else CFG.STRUCTURE_ADX_MIN
    r = run_test('structure_break',syms,'5m',trail_act=0.4,trail_pct=0.22)
    print(f'  {label:<50} T={r["trades"]:>3} W={r["wins"]:>2} WR={r["wr"]:>4.0f}% PF={r["pf"]:>5.2f} PnL=${r["pnl"]:>+8.2f}')
    return r

ACTUALES = ['FILUSDT','DOGEUSDT','APTUSDT','WIFUSDT','ATOMUSDT']
NUEVOS_A = ['ETHUSDT','ORDIUSDT','XRPUSDT','SOLUSDT','LINKUSDT']
NUEVOS_B = ['AVAXUSDT','PENDLEUSDT','NEARUSDT','1000PEPEUSDT','TIAUSDT']
NUEVOS_C = ['SUIUSDT','BTCUSDT','OPUSDT','SANDUSDT','TAOUSDT']
MIX_A = ['FILUSDT','ETHUSDT','DOGEUSDT','ORDIUSDT','APTUSDT']
MIX_B = ['WIFUSDT','ATOMUSDT','XRPUSDT','SOLUSDT','LINKUSDT']
MIX_C = ['AVAXUSDT','PENDLEUSDT','NEARUSDT','SUIUSDT','BTCUSDT']

batch = sys.argv[1] if len(sys.argv)>1 else '1'

if batch=='1':
    print(f'\n{"="*80}\n  STRUCTURE BREAK BATCH 1: Params con símbolos actuales (BACKTESTING_LOG)\n{"="*80}')
    run('BASE (Sw5/Look60/Break10/Vol2/ADX15)',ACTUALES)
    run('Sw3/Look30/Break5/Vol3/ADX25',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=25)
    run('Sw3/Look30/Break5/Vol3/ADX20',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=20)
    run('Sw3/Look30/Break5/Vol2/ADX20',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':2.0},adx=20)
    run('Sw3/Look30/Break5/Vol2/ADX25',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':2.0},adx=25)
    run('Sw5/Look60/Break10/Vol2.5/ADX20',ACTUALES,{'STRUCTURE_MIN_BREAK_VOLUME':2.5},adx=20)
    run('Sw5/Look60/Break10/Vol2.5/ADX18',ACTUALES,{'STRUCTURE_MIN_BREAK_VOLUME':2.5},adx=18)

if batch=='2':
    print(f'\n{"="*80}\n  STRUCTURE BREAK BATCH 2: Más parámetros\n{"="*80}')
    run('SWING 3',ACTUALES,{'STRUCTURE_SWING_WINDOW':3})
    run('SWING 7',ACTUALES,{'STRUCTURE_SWING_WINDOW':7})
    run('LOOKBACK 30',ACTUALES,{'STRUCTURE_LOOKBACK':30})
    run('LOOKBACK 90',ACTUALES,{'STRUCTURE_LOOKBACK':90})
    run('BREAK 5',ACTUALES,{'STRUCTURE_BREAK_LOOKBACK':5})
    run('BREAK 15',ACTUALES,{'STRUCTURE_BREAK_LOOKBACK':15})
    run('BREAK_VOL 1.5',ACTUALES,{'STRUCTURE_MIN_BREAK_VOLUME':1.5})
    run('BREAK_VOL 3.0',ACTUALES,{'STRUCTURE_MIN_BREAK_VOLUME':3.0})

if batch=='3':
    print(f'\n{"="*80}\n  STRUCTURE BREAK BATCH 3: Retest, SL, ADX\n{"="*80}')
    run('RETEST 5',ACTUALES,{'STRUCTURE_RETEST_LOOKBACK':5})
    run('RETEST 12',ACTUALES,{'STRUCTURE_RETEST_LOOKBACK':12})
    run('TOL 0.3',ACTUALES,{'STRUCTURE_RETEST_TOLERANCE_ATR':0.3})
    run('TOL 0.8',ACTUALES,{'STRUCTURE_RETEST_TOLERANCE_ATR':0.8})
    run('SL_BUF 0.5',ACTUALES,{'STRUCTURE_SL_BUFFER_ATR':0.5})
    run('SL_BUF 1.5',ACTUALES,{'STRUCTURE_SL_BUFFER_ATR':1.5})
    run('ADX 12',ACTUALES,adx=12)
    run('ADX 18',ACTUALES,adx=18)

if batch=='4':
    print(f'\n{"="*80}\n  STRUCTURE BREAK BATCH 4: Combinaciones restrictivas\n{"="*80}')
    run('Sw3/Look30/Bk5/Vol3/ADX25/Tol0.3',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0,'STRUCTURE_RETEST_TOLERANCE_ATR':0.3},adx=25)
    run('Sw3/Look30/Bk5/Vol3/ADX20/Tol0.3',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0,'STRUCTURE_RETEST_TOLERANCE_ATR':0.3},adx=20)
    run('Sw3/Look30/Bk5/Vol2.5/ADX20/Tol0.5',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':2.5},adx=20)
    run('Sw5/Look60/Bk10/Vol2.5/ADX20/Tol0.3',ACTUALES,{'STRUCTURE_MIN_BREAK_VOLUME':2.5,
        'STRUCTURE_RETEST_TOLERANCE_ATR':0.3},adx=20)
    run('Sw5/Look60/Bk10/Vol3/ADX20',ACTUALES,{'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=20)

if batch=='5':
    print(f'\n{"="*80}\n  STRUCTURE BREAK BATCH 5: Combinaciones relajadas\n{"="*80}')
    run('Sw3/Look30/Bk5/Vol1.5/ADX12',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':1.5},adx=12)
    run('SWING3+ADX12',ACTUALES,{'STRUCTURE_SWING_WINDOW':3},adx=12)
    run('BREAK5+VOL1.5',ACTUALES,{'STRUCTURE_BREAK_LOOKBACK':5,'STRUCTURE_MIN_BREAK_VOLUME':1.5})
    run('TOL0.8+ADX12',ACTUALES,{'STRUCTURE_RETEST_TOLERANCE_ATR':0.8},adx=12)
    run('TODO RELAJADO',ACTUALES,{'STRUCTURE_SWING_WINDOW':3,'STRUCTURE_LOOKBACK':30,
        'STRUCTURE_BREAK_LOOKBACK':5,'STRUCTURE_MIN_BREAK_VOLUME':1.5,
        'STRUCTURE_RETEST_TOLERANCE_ATR':0.8},adx=12)

if batch=='6':
    print(f'\n{"="*80}\n  STRUCTURE BREAK BATCH 6: Nuevos símbolos A\n{"="*80}')
    run('NUEVOS_A base',NUEVOS_A)
    run('NUEVOS_A restrictivo',NUEVOS_A,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=25)
    run('NUEVOS_A medio',NUEVOS_A,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':2.0},adx=20)
    run('NUEVOS_A relajado',NUEVOS_A,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':1.5},adx=12)
    run('NUEVOS_B base',NUEVOS_B)
    run('NUEVOS_B restrictivo',NUEVOS_B,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=25)

if batch=='7':
    print(f'\n{"="*80}\n  STRUCTURE BREAK BATCH 7: Nuevos símbolos B + C\n{"="*80}')
    run('NUEVOS_B medio',NUEVOS_B,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':2.0},adx=20)
    run('NUEVOS_C base',NUEVOS_C)
    run('NUEVOS_C restrictivo',NUEVOS_C,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=25)
    run('NUEVOS_C medio',NUEVOS_C,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':2.0},adx=20)
    run('NUEVOS_C relajado',NUEVOS_C,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':1.5},adx=12)

if batch=='8':
    print(f'\n{"="*80}\n  STRUCTURE BREAK BATCH 8: Mix\n{"="*80}')
    run('MIX_A base',MIX_A)
    run('MIX_A restrictivo',MIX_A,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=25)
    run('MIX_B base',MIX_B)
    run('MIX_B restrictivo',MIX_B,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=25)
    run('MIX_C base',MIX_C)
    run('MIX_C restrictivo',MIX_C,{'STRUCTURE_SWING_WINDOW':3,
        'STRUCTURE_LOOKBACK':30,'STRUCTURE_BREAK_LOOKBACK':5,
        'STRUCTURE_MIN_BREAK_VOLUME':3.0},adx=25)

print(f'\n  Uso: ./venv/bin/python bt_sb_batches.py [1-8]')
